service : nestjs-serverless-app

frameworkVersion : '3'

provider:
  name : aws
  runtime : nodejs16.x
  region : us-east-1
  memorySize: 128
  timeout: 15

functions:
  api:
   handler: dist/lambda.handler
   events:

     - httpApi:
         method: any
         path : /

     - httpApi:
         method: any
         path : /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
